version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/go-pg/pg/v10
    versions:
    - 10.7.4
    - 10.7.5
    - 10.7.6
    - 10.7.7
    - 10.8.0
    - 10.9.0
  - dependency-name: github.com/go-redis/redis/v8
    versions:
    - 8.4.11
    - 8.5.0
    - 8.6.0
    - 8.7.1
    - 8.8.0
  - dependency-name: github.com/lib/pq
    versions:
    - 1.10.0
    - 1.9.0
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: github.com/prometheus/client_golang
    versions:
    - 1.9.0
