language: go
go:
  - "1.12"
  - master
services:
  - redis-server
before_install:
  - go get github.com/mattn/goveralls
env:
  - GO111MODULE=on  
script:
  - "$HOME/gopath/bin/goveralls -service=travis-ci"