name: ci
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
  test:
    runs-on: ubuntu-latest
    container: golang:1.24.2-alpine3.21
    services:
      redis:
        image: redis
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Install common dependencies
        run: apk add --no-cache gcc libc-dev
      - uses: actions/checkout@v4
      - run: go test -v ./...
        env:
          REDIS_ADDR: redis:6379
          DATABASE_ADDR: postgres:5432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_DATABASE: postgres
          DATABASE_SSL: false
